export const CHANGE_SEARCH_FIELD: string = 'CHANGE_SEARCH_FIELD';
export const REQUEST_ROBOT_PENDING: string = 'REQUEST_ROBOT_PENDING';
export const REQUEST_ROBOT_SUCCESS: string = 'REQUEST_ROBOT_SUCCESS';
export const REQUEST_ROBOT_FAILED: string = 'REQUEST_ROBOT_FAILED';